source 'https://rubygems.org'

gem 'rspec'
gem 'allure-rspec'
gem 'json'
gem 'require_all'
gem 'rest-client'
gem 'rspec_junit_formatter'
gem 'parallel'
gem 'celluloid'
gem 'parallel_tests'
gem 'concurrent-ruby'
gem 'json_refs'
gem 'json-schema'
gem 'pry'
gem 'concurrent-ruby'
